apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      tier: postgres  # Corrected typo in 'postgres'
  strategy:  # Corrected spelling of 'strategy'
    type: Recreate    
  template:
    metadata:
      labels:
        app: django
        tier: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.2  # Corrected typo in 'postgres'
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: djangodb
        - name: POSTGRES_USER
          value: djangouser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
               name: db-password
               key: password
